### ISSUE TITLE
UI Issue in safari top bar has color mismatch

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-web-leptos-ssr#121]
## Description
The screen in safari, top bar shows orange color.

![IMG_FAB2A832E579-1](https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/assets/152961362/35b8ea1f-15b3-4688-9bee-735976cd1759)

**Comment by rupansh-gob** [comment]
need to update https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/blob/main/public/app.webmanifest
