### ISSUE TITLE
Fix title and favicon on all pages

### ISSUE THREAD

**Issue by saikatdas0790** [go-bazzinga/hot-or-not-web-leptos-ssr#134]
![image](https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/assets/7412443/c132439c-101d-40af-9ded-d795ad90f729)

**Comment by rupansh-gob** [comment]
duplicate https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/issues/45
