### ISSUE TITLE
Update Privacy Policy and Terms of Service

### ISSUE THREAD

**Issue by saikatdas0790** [go-bazzinga/hot-or-not-web-leptos-ssr#135]
https://yral.com/terms-of-service

https://yral.com/privacy-policy

@Diksha894 Can you provide the updated writeups for these ^

Needs to incorporate these sections for Google Auth approval
![image](https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/assets/7412443/b26e8acb-7f56-49fb-9ac2-cf0b0dff647b)

**Comment by Diksha894** [comment]
@komal-rs 
Update the following in the app menu
1. Privacy Policy
https://docs.google.com/document/d/1TRhPFeTu4hDp2_xidlNsJKgLp_zIJz51RbkfmWZxafw/edit?usp=sharing

2. Terms of Service
https://docs.google.com/document/d/1PzJahni-6c7wZ8HZkx2FDH8kxRPbVNiaYC7yivacidk/edit?usp=sharing
