### ISSUE TITLE
[BUG] not able view videos from user profile and profile is not aligned properly

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-web-leptos-ssr#148]
## Description

Video is not clickable in below screenshot

<img width="1088" alt="Screenshot 2024-03-27 at 1 15 56 PM" src="https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/assets/152961362/c88d46e9-1cff-435e-b597-ce0909106b73">

**Comment by rupansh-gob** [comment]
fixed by https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/pull/221
