### ISSUE TITLE
Add Logout CTA in Menu

### ISSUE THREAD

**Issue by Diksha894** [go-bazzinga/hot-or-not-web-leptos-ssr#150]
Add a Logout CTA in menu along these lines:
https://www.figma.com/file/ig9dxeJrajuzHNGlo4zUps/experiment-file?type=design&node-id=567-10529&mode=design&t=wpsU0nh5OFQ2DuFg-4

@komal-rs

**Comment by komal-rs** [comment]
Fixed by #156

**Comment by komal-rs** [comment]
Fixed by https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/pull/156
