### ISSUE TITLE
Share Button → Go to native share window

### ISSUE THREAD

**Issue by rosarp-gobazzinga** [go-bazzinga/hot-or-not-web-leptos-ssr#192]
### Current State

Share button on videos → Leads to a copy link option

### Ideal State

Share button click → Opens Native Share window so that user can directly send it on their social apps, or copy link depending on their OS

In case native share window is not opening → copy link option

**Comment by rupansh** [comment]
![image](https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/assets/3929608/a95f6c56-5082-4419-b8ef-82f86fad1856)

Working on my phone
Android 14
Chrome
