### ISSUE TITLE
HotorNot Game Implementation in YRAL app

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#242]
**What are we trying to do?**
We are planning to introduce the HOTorNOT game in the YRAL app

**Why do we want to do this?**
We want to do because we have seen great engagement (<Number to be added>) on HOTorNOT app when we had gamefied the user experience. We feel adding this game in YRAL will ensure we have an experience available with users to engage with the reels they are seeing on the platform.

**How do we want to do this?**
All details have been addded in the PRD along with the Figma link. [https://www.notion.so/gobazzinga/HotorNot-Game-Implementation-4fd67cd057614d2284375052507fbc31?pvs=4](url)

**Comment by abeeshake-yral** [comment]
track backend PR here: https://github.com/go-bazzinga/hot-or-not-backend-canister/pull/330

Expected to close the PR this week.

**Comment by abeeshake-yral** [comment]
closing this in favour of #251
