### ISSUE TITLE
[Content Seeding] Add a page for youtube upload

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-web-leptos-ssr#244]
## Description
Add a page to submit youtube urls to node server to upload videos. This page should be only for internal authorised members. The list can be fetched from the node server.

**Comment by harshitasrivastav28** [comment]
- We should get option for YRAL webapp when user clicks on "Share" on the youtube reels.

**Comment by ravibazz** [comment]
Blocked on https://github.com/go-bazzinga/download-upload-service/issues/1

**Comment by Natasha-GB** [comment]
- Reviews pending
