### ISSUE TITLE
[UI/UX] Hide "Lovers" and "Loving" on User Profiles

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-web-leptos-ssr#270]
Current Implementation: "Lovers" and "Loving" count is 0 for all, we don't have the option to follow someone at present on YRAL
Quick Workaround: Hide both the sections and show only Hot/Not Counts
Requirement -
1. Remove Lovers and Loving count
2. Modify UI to align Hot and Not count only

_Future Plan: Have an intelligent "Follow" feature with DS-backed suggestions implemented_

**Comment by harshitasrivastav28** [comment]
- Deployed on staging (@Natasha-GB to give go ahead for prod deployment)

**Comment by Natasha-GB** [comment]
Verified @ravibazz 

- No Follow/Love Button
- Lover/Loving Count Hidden
- UI for Hots and Nots looks aligned

![Image](https://github.com/user-attachments/assets/0b606cd5-c9f0-46fc-8c50-662a4adbd750)
