### ISSUE TITLE
Updating error copies on frontend

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#275]
Problem statement: Whenever there is an error in any flow on the app, the frontend display "Something went wrong" along with the subtext too technical for the users to understand. This doesn't give context to users on what error has occurred and how can they rectify it.

How to solve it?

- We will collate the list of frontend and backend errors codes and copy being displayed in the system as of today.[ (Error List and its frequency in last 30 days)](https://docs.google.com/spreadsheets/d/1ZsCrQ2R3PUkLjWkxr1BxhE-nCcefFqwW6xAbAe0tARo/edit?gid=1572104246#gid=1572104246)
- We will map these errors codes to a specific copy on the frontend.
- E.g.: If user's video upload has failed due to some server error, instead of showing "Somethign went wrong" we will show "We could not upload you video. Please retry" and a CTA for "Retry"

**Expectation from tech**

- Please share the list and type of frontend errors (Preferably in the order of their frequency)
- Product team will map the copies of these error which can be shown on frontend
- Tech team to reduce the error frequency and do RCA
- Tech to map these copies with desired error codes.

Attaching the error screenshot as it appears today on the app.

![Image](https://github.com/user-attachments/assets/cbf1a94f-d649-4a0c-940d-5ad7272074fe)

**Comment by harshitasrivastav28** [comment]
- String match and show a relevant copy.
- Missing is to have an offline strategy

**Comment by harshitasrivastav28** [comment]
- For now pass the string and get the copy updated on the frontend

**Comment by prakash-bhatt-rs** [comment]
Here, we will be using pattern matching over the err string and based on that we will map error into the user readable text which is to be displayed on the ServerErrorPage component.

E.g.

impl ServerErrParams {
    fn map_to_err(&self) -> String {
        match self.err.as_str() {
            _ if self.err.contains("IC agent error") => "Network Error".to_string(),
            _ => self.err.clone(),
        }
    }
}

**Comment by Natasha-GB** [comment]
- Understanding of errors and corresponding messages to users
- To connect with @rupansh-gob for the same

**Comment by harshitasrivastav28** [comment]
@prakash-bhatt-rs Please find the final design of the error page. https://www.figma.com/design/ROOZI0htIyu8kODvVXz0IB/New-Project?node-id=742-8370&t=PHJcKRQm1vJ5Nl2u-4
