### ISSUE TITLE
Heart icon on Homepage gets enlarged when selected

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#276]
Problem statement: As a user, when I select the "Heart icon" on the homefeed to like a video, the icon gets cut at the bottom

Solution: We should understand why the issue is happening and one probable solution can we increase the padding between the icons on the app.

Attaching a video for reference

https://github.com/user-attachments/assets/0841cd46-d7ae-41b4-a068-465c65f5df8f

**Comment by harshitasrivastav28** [comment]
- Add overlap component link this task @rupansh-gob to share

**Comment by harshitasrivastav28** [comment]
- Going through the code base
- Understood the problem statement from PM

**Comment by Natasha-GB** [comment]
- To connect with @rupansh-gob
