### ISSUE TITLE
Like Count on Feed is reset post navigation to other pages

### ISSUE THREAD

**Issue by Natasha-GB** [go-bazzinga/hot-or-not-web-leptos-ssr#277]
If you like a video on feed > Then navigate to some other page like wallet/menu > When you return to the same video on feed, the Like Count is reset even though you've already liked the Video

Ideal Flow - Like Icon should be in selected state and the count updated to incorporate my like when I return to feed from a different page

https://github.com/user-attachments/assets/5a7b7ccc-123c-4e2a-963f-1926749f18dc

**Comment by harshitasrivastav28** [comment]
- Adarsh to be assigned to this task

**Comment by harshitasrivastav28** [comment]
- Going through the code
- Mention the current end points 
- What all changes are to be done in the endpoints
- Suggestion: Make a new end point which is common for updating the status as well as maintaining the counter of likes.
- This will ensure we don't have differential behaviour when upgrading the canisters.

**Comment by Natasha-GB** [comment]
Assign review to another spoc @adarsh-rs

**Comment by harshitasrivastav28** [comment]
- @adarsh-rs to get this work approved by PM

**Comment by Natasha-GB** [comment]
Flow validated, good to go. @adarsh-rs
