### ISSUE TITLE
Buggy Login Overlay Experience

### ISSUE THREAD

**Issue by Natasha-GB** [go-bazzinga/hot-or-not-web-leptos-ssr#283]
Go to any other page on the app > Navigate back to feed > Scroll down once > Login pop-up reappears

To be noted -
1. For Non logged-in user
2. Has to shuffle between a page and the feed to have a recurring buggy UX

_Ideal Flow: Overlay/Pop-up can appear based on the number of scrolls counter_

**Comment by harshitasrivastav28** [comment]
- Natasha to add video in this issue

**Comment by Natasha-GB** [comment]
- Work started
- Index related clarification - discuss with Ravi

**Comment by harshitasrivastav28** [comment]
- Get this verified with PM

**Comment by Natasha-GB** [comment]
Validated flow, good to go. @adarsh-rs
