### ISSUE TITLE
A/B Experimentation Implementation | Phase 1

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#302]
_Proposal -_

- Server-side rendering since it fares much better when it comes to latency as compared to client side rendering and can be scaled to a large number of users
- We will take it up in 2 phases, first phase involving BigQuery and based on latency evaluation, we'll see if caching on redis is required in the second phase

**Comment by Veercodeprog** [comment]
Hi @harshitasrivastav28 
I'm really interested in contributing to the server-side rendering initiative and the phased approach involving BigQuery and Redis.I’m keen to get started, but I wanted to check if there are any specific credentials or access requirements needed for integrating with Redis and BigQuery. Also, Understanding the authentication and access setup will help me align my contributions effectively.
Any additional context or documentation on the current setup would also be helpful.

**Comment by debjit-bhowal-rs** [comment]
Implemented framework for AB testing:
- Currently it's functional, given a closure that resolves into a string, it will choose the respective component and display
- Need to add the specifics of how to do that, for eg from bigquery or any source

Next steps:
- The actual integration, with principal ids

**Comment by debjit-bhowal-rs** [comment]
USAGE:

earlier:

```rs
    view! {
        <Scroller />
    }
```

now:

```rs
    view! {
        let component_1: ABComponent = Box::new(<Scroller1 />);
        let component_2: ABComponent = Box::new(<Scroller2 />);
        let component_3: ABComponent = Box::new(<Scroller3 />);
        abselector!(/* closure returning string */, component_1, component_2, component_3)()
    }
```
