### ISSUE TITLE
Push Notification v2

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#330]
- Handling back to back notifications for a single event (Group and send - logic to be decided)
- Identifying nudges for enabling push notifications

**Comment by harshitasrivastav28** [comment]
- Add the permission for PN inside the setting
- Don't put it on the login flow

**Comment by debjit-bhowal-rs** [comment]
![Image](https://github.com/user-attachments/assets/113879dd-9297-4968-865d-045d984a1a9c)

**Comment by Natasha-GB** [comment]
- Create Settings as an Entry > Push Notifications to go underneath
