### ISSUE TITLE
Setting SNS field default limits for Creator DAO launch readiness

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-web-leptos-ssr#332]
This project has 2 tasks

- [x] #333
- [x] #334

List of SNS fields: https://www.notion.so/gobazzinga/SNS-Fields-and-limits-6ac73b3b6b3445c0a1a3d5a7c2383e49

Readme for SNS field understanding: https://github.com/dfinity/sns-testing/blob/main/example_sns_init.yaml#L322

Current configuration:
https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/blob/rupansh/cdao/ssr/src/page/token/sns_form.rs#L95

**Comment by Veercodeprog** [comment]
does sns fields value needs to be updated in the notion docs or sns_form.rs for now?

**Comment by Veercodeprog** [comment]
https://gist.github.com/Veercodeprog/e7d38b1d6f16a71ca9549118487400cd

**Comment by Veercodeprog** [comment]
in this ,i have created the categorised subfields listings which are based under a field categorised.
https://gist.github.com/Veercodeprog/f339c24e093084c42e6a92b8b3d9c219
also whats our ultimate goal here,
do we need to add in docs or update rust code in the sns_form.rs to output values based on it.

**Comment by harshitasrivastav28** [comment]
- @debjit-bhowal-rs is helping in filling the notion for Min Max values

**Comment by debjit-bhowal-rs** [comment]
Hey @Veercodeprog, I went through your gist. I think some params are wrong, for example the minimum dissolve delay you specified is 1 day, but if you see [this document](https://internetcomputer.org/docs/current/developer-docs/daos/sns/tokenomics/rewards#:~:text=Required%20minimum%20dissolve%20delay%20for%20voting%20ddmin), it's specified as 0. Can you re-verify your parameters once?

**Comment by Veercodeprog** [comment]
you are correct , 
i referred from the example yaml file, theres no value marked for it , i set it to 0 
i will check the document in detail ,
Thanks

**Comment by debjit-bhowal-rs** [comment]
ah, the above yaml file is just an exemplar default

**Comment by harshitasrivastav28** [comment]
- Deployed the local
- Fontend task is left which will be closed today.
- Update backend canister as the SNS proposal has changed after that

**Comment by harshitasrivastav28** [comment]
- Token creation default option (minimum) token is getting created.
- Reviewed with Saikat.
- Balance was not getting updated (Fetching issue or claim the balance manually)
- Post that focus on UI of advance setting

**Comment by harshitasrivastav28** [comment]
- Token allocation is not happening which we are trying to fix
-
