### ISSUE TITLE
HON Onboarding/Tutorial

### ISSUE THREAD

**Issue by Natasha-GB** [go-bazzinga/hot-or-not-web-leptos-ssr#374]

**Comment by Natasha-GB** [comment]
- Will be created from scratch

**Comment by harshitasrivastav28** [comment]
- We will be able to fix the 1st page by EOD

**Comment by Natasha-GB** [comment]
- 3 pages on FE done
- BE logic to be implemented today

**Comment by harshitasrivastav28** [comment]
- Backend changes have been done
- Working on frontend logic

**Comment by harshitasrivastav28** [comment]
- Complete development
- Demo was shown

**Comment by harshitasrivastav28** [comment]
- @rupansh to review the onboarding flow PR and then we can take a call
