### ISSUE TITLE
Upload button blends with white background

### ISSUE THREAD

**Issue by rosarp-gobazzinga** [go-bazzinga/hot-or-not-web-leptos-ssr#54]
For video - emkfb-7qaaa-aaaao-aapeq-cai/552
the bottom portion is white. so upload button blends in and is not visible.

**Comment by rupansh-gob** [comment]
related https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/issues/42

**Comment by rupansh-gob** [comment]
Fixed with https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/pull/100
