### ISSUE TITLE
UI/UX Changes before release

### ISSUE THREAD

**Issue by Diksha894** [go-bazzinga/hot-or-not-web-leptos-ssr#91]
### Pages to add
- [ ] #92
- [x] #93

### UI Changes on Navigation Bar
- [x] Update the color and fill of icons to match the design provided. Refer to [this screen](https://www.figma.com/file/ig9dxeJrajuzHNGlo4zUps/experiment-file?type=design&node-id=492-3358&mode=design&t=lMhd2ODjT8gtsmL6-4) for reference.
- [x] Modify the highlighted state as per the provided design. Add a pink bar on top of the icon and fill the icon with white color, consistent with the design specifications.

### UI changes on Home screen
- [x] Home screen title button at the top
- [x] Add all 5 buttons to navigation bar
- [x] Navigation bar proportions reset [too small currently]
- [x] Navigation bar make more prominent
- [x] Like, Share, Refer and Earn on the right hand side
- [x] Profile Icon, Profile Name and Description on the left hand side
- [x] Video Description not opening on click
- [ ] Add YRAL logo watermark on top left of screen
- [x] Change the color of home button on top of the screen according to [this screen](https://www.figma.com/file/ig9dxeJrajuzHNGlo4zUps/experiment-file?type=design&node-id=492-3358&mode=design&t=lMhd2ODjT8gtsmL6-4) 

### UI Changed on Menu Screen
- [x] Navigation Bar to show up here as well - more prominently
- [x] #98
- [x] Social connect section on mobile is too big for the screen
- [x] Remove Airdrop, About us and FAQ section
- [x] Login CTA - add description according to [this screen](https://www.figma.com/file/ig9dxeJrajuzHNGlo4zUps/experiment-file?type=design&node-id=495-5853&mode=design&t=lMhd2ODjT8gtsmL6-4)

### UI changes on profile page
- [x] Add "no videos to show" page
- [x] Add "coming soon" page to bets section
- [x] Add Back Button on top left
- [x] Create not logged-in state according to [this screen](https://www.figma.com/file/ig9dxeJrajuzHNGlo4zUps/experiment-file?type=design&node-id=505-7800&mode=design&t=lMhd2ODjT8gtsmL6-4)
- [x] Placement of elements is only in the center on mobile, sides of the screen are empty

**Comment by rupansh-gob** [comment]
related: https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/issues/42
